<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */
return array(
    'ZF\\Apigility',
    'ZF\\Apigility\\Provider',
    'ZF\\ApiProblem',
    'ZF\\MvcAuth',
    'ZF\\OAuth2',
    'ZF\\Hal',
    'ZF\\ContentNegotiation',
    'ZF\\ContentValidation',
    'ZF\\Rest',
    'ZF\\Rpc',
    'ZF\\Versioning',
    'ZF\\DevelopmentMode',
    'Zend\\Log',
    'Zend\\Form',
    'Zend\\Db',
    'Zend\\Cache',
    'Zend\\Filter',
    'Zend\\Hydrator',
    'Zend\\InputFilter',
    'Zend\\Mail',
    'Zend\\Navigation',
    'Zend\\Paginator',
    'Zend\\Router',
    'Zend\\Session',
    'Zend\\ServiceManager\\Di',
    'Zend\\Validator',
    'Application',
    'AssetManager',
    'Login',
);
